// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeeZow_rY9dJ4y4H0mpyukTRXqWO6lOMQ',
    appId: '1:462291302073:web:f48bfcfd6f19d307358d68',
    messagingSenderId: '462291302073',
    projectId: 'flutter-egitim',
    authDomain: 'flutter-egitim.firebaseapp.com',
    storageBucket: 'flutter-egitim.appspot.com',
    measurementId: 'G-79KESTV63F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMWTfakGOF-4qrOd4NMKtX8C7V0d1fxtg',
    appId: '1:462291302073:android:bc83d4b1e677144c358d68',
    messagingSenderId: '462291302073',
    projectId: 'flutter-egitim',
    storageBucket: 'flutter-egitim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ2ttr7ZSXuFztlmIm5ZXTye-phnT0PZY',
    appId: '1:462291302073:ios:0dd103898b0ae1ee358d68',
    messagingSenderId: '462291302073',
    projectId: 'flutter-egitim',
    storageBucket: 'flutter-egitim.appspot.com',
    iosBundleId: 'com.example.mapFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ2ttr7ZSXuFztlmIm5ZXTye-phnT0PZY',
    appId: '1:462291302073:ios:4c84facf4aeaac15358d68',
    messagingSenderId: '462291302073',
    projectId: 'flutter-egitim',
    storageBucket: 'flutter-egitim.appspot.com',
    iosBundleId: 'com.example.mapFlutter.RunnerTests',
  );
}
